name: CapRover App Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    uses: floms/action-caprover@v1
    with:
      host: 'https://captain.blog.kenshuri.com'
      password: '${{ secrets.CAPROVER_PASSWORD }}'
      app: 'from-github'
      branch: 'main'
